name: single_hand_shake_protocol
repository: https://github.com/lgualandi/SingleHandShakeProtocolDart

packages:
  - packages/**

scripts:
  compile:
    description: Generate code with build_runner for all packages using json_serializable
    run: melos exec --depends-on=json_serializable -- dart run build_runner build --delete-conflicting-outputs
  
  compile:watch:
    description: Generate code with build_runner in watch mode for all packages using json_serializable
    run: melos exec --depends-on=json_serializable -- dart run build_runner watch --delete-conflicting-outputs
  
  test:
    description: Run all tests
    run: melos exec -c 1 --scope="shsp_tests" -- dart test
  
  analyze:
    description: Analyze all packages
    run: melos exec -- dart analyze
  
  format:
    description: Format all Dart files
    run: melos exec -- dart format .
  
  get:
    description: Get dependencies for all packages
    run: melos exec -- dart pub get
  
  clean:
    description: Clean all packages
    run: melos clean
