name: single_hand_shake_protocol_monorepo
description: A Dart monorepo for Single HandShake Protocol
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  shsp_types:
    path: packages/types
  shsp_interfaces:
    path: packages/interfaces
  shsp_implementations:
    path: packages/implementations
  stun: 1.0.1
  json_serializable: ^6.11.1
  build_runner: ^2.10.4

dev_dependencies:
  melos: ^3.4.0
  lints: ^3.0.0
  test: ^1.24.0
