name: shsp_implementations
description: Implementations for Single HandShake Protocol
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  json_annotation: ^4.9.0
  shsp_types:
    path: ../types
  shsp_interfaces:
    path: ../interfaces
  meta: ^1.17.0
  cryptdart: ^0.1.0

  clock_dart: ^1.0.0
  stun: ^1.0.0

dev_dependencies:
  build_runner: ^2.10.2
  json_serializable: ^6.11.1
  lints: ^3.0.0
  test: ^1.24.0
  index_generator: 4.1.2
